services:
  - type: web
    name: music-library
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: PGDATABASE
        fromDatabase:
          name: production
          property: database
      - key: PGUSER
        fromDatabase:
          name: production
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: production
          property: password
      - key: PGHOST
        fromDatabase:
          name: production
          property: host
      - key: PGPORT
        fromDatabase:
          name: production
          property: port



databases:
  - name: production
    databaseName: music_library
    region: frankfurt
    plan: free
    ipAllowList: []
